# Generated by Django 4.2.28 on 2026-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='casual_leaves',
            field=models.IntegerField(default=10, help_text='Remaining casual leave days'),
        ),
        migrations.AddField(
            model_name='user',
            name='earned_leaves',
            field=models.IntegerField(default=12, help_text='Remaining earned leave days'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_leaves',
            field=models.IntegerField(default=15, help_text='Remaining medical leave days'),
        ),
    ]
