# Generated by Django 4.2.28 on 2026-02-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('medical', 'Medical Leave'), ('maternity', 'Maternity Leave'), ('eol', 'EOL')], default='annual', help_text='Type of leave requested', max_length=20),
        ),
    ]
