# Generated by Django 4.2.28 on 2026-02-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_alter_leaverequest_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='deducted',
            field=models.BooleanField(default=False, help_text='Whether the leave days were deducted from employee balance'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave'), ('earned', 'Earned Leave'), ('medical', 'Medical Leave'), ('maternity', 'Maternity Leave'), ('eol', 'EOL')], default='casual', help_text='Type of leave requested', max_length=20),
        ),
    ]
